from __future__ import annotations

from typing import Any

from .contract import TranscriptionRequest


def transcribe(request: TranscriptionRequest) -> dict[str, Any]:
    """Return deterministic output for contract and worker integration tests."""

    language = "en" if request.language == "auto" else request.language
    return {
        "contract_version": "1",
        "language": language,
        "language_probability": 0.99,
        "duration_ms": 4_200,
        "model": {
            "engine": "fake",
            "name": request.model,
            "revision": "milestone-2-fake",
        },
        "segments": [
            {
                "start_ms": 400,
                "end_ms": 2_100,
                "text": "Build the rhythm",
                "words": [
                    {
                        "text": "Build",
                        "start_ms": 400,
                        "end_ms": 900,
                        "confidence": 0.99,
                    },
                    {
                        "text": "the",
                        "start_ms": 920,
                        "end_ms": 1_200,
                        "confidence": 0.99,
                    },
                    {
                        "text": "rhythm",
                        "start_ms": 1_220,
                        "end_ms": 2_100,
                        "confidence": 0.99,
                    },
                ],
            },
            {
                "start_ms": 2_250,
                "end_ms": 3_900,
                "text": "Render the story",
                "words": [
                    {
                        "text": "Render",
                        "start_ms": 2_250,
                        "end_ms": 2_850,
                        "confidence": 0.99,
                    },
                    {
                        "text": "the",
                        "start_ms": 2_870,
                        "end_ms": 3_100,
                        "confidence": 0.99,
                    },
                    {
                        "text": "story",
                        "start_ms": 3_120,
                        "end_ms": 3_900,
                        "confidence": 0.99,
                    },
                ],
            },
        ],
        "warnings": ["Generated by the deterministic Milestone 2 fake adapter"],
    }
