/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Process liveness */
        get: operations["getLiveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dependency and capability readiness */
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List projects for the current owner */
        get: operations["listProjects"];
        put?: never;
        /** Create a lyric-video project */
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        /** Get a project */
        get: operations["getProject"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update project metadata or default video settings */
        patch: operations["updateProject"];
        trace?: never;
    };
    "/projects/{project_id}/assets": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload or replace the project's source audio or background image
         * @description The API streams the multipart body, computes a checksum, performs initial
         *     validation, and makes the new asset active only after the write succeeds.
         */
        post: operations["uploadProjectAsset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/transcriptions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start word-level transcription of the active audio asset */
        post: operations["startTranscription"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/transcript": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        /** Get the active immutable transcript revision */
        get: operations["getActiveTranscript"];
        /** Save edits as a new immutable transcript revision */
        put: operations["replaceActiveTranscript"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/renders": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a video render from a pinned transcript revision */
        post: operations["startRender"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/renders/{render_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get render metadata and result */
        get: operations["getRender"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current durable job state */
        get: operations["getJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream job snapshots and progress with Server-Sent Events
         * @description Event names are `progress`, `succeeded`, `failed`, and `cancelled`.
         *     Each `data` field is a JSON JobEvent. Clients should reconnect with
         *     `Last-Event-ID` and fall back to GET /jobs/{job_id} when streaming is unavailable.
         */
        get: operations["streamJobEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request cancellation of a queued or running job */
        post: operations["cancelJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/artifacts/{artifact_id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download an authorized project artifact */
        get: operations["downloadArtifact"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Format: uuid */
        Uuid: string;
        /** Format: date-time */
        Timestamp: string;
        HealthResponse: {
            /** @constant */
            status: "ok";
        };
        ReadinessResponse: {
            /** @enum {string} */
            status: "ready" | "not_ready";
            checks: components["schemas"]["ReadinessCheck"][];
        };
        ReadinessCheck: {
            /** @example database */
            name: string;
            ready: boolean;
            detail?: string | null;
        };
        CreateProjectRequest: {
            name: string;
            video_settings?: components["schemas"]["VideoSettings"];
        };
        UpdateProjectRequest: {
            name?: string;
            video_settings?: components["schemas"]["VideoSettings"];
        };
        /** @enum {string} */
        ProjectStatus: "draft" | "ready" | "rendering" | "completed" | "failed";
        Project: {
            id: components["schemas"]["Uuid"];
            name: string;
            status: components["schemas"]["ProjectStatus"];
            video_settings: components["schemas"]["VideoSettings"];
            audio_asset?: components["schemas"]["Asset"] | null;
            background_asset?: components["schemas"]["Asset"] | null;
            active_transcript_revision?: number | null;
            latest_render_id?: components["schemas"]["Uuid"] | null;
            created_at: components["schemas"]["Timestamp"];
            updated_at: components["schemas"]["Timestamp"];
        };
        ProjectPage: {
            items: components["schemas"]["Project"][];
            next_cursor: string | null;
        };
        VideoSettings: {
            /** @default 1920 */
            width: number;
            /** @default 1080 */
            height: number;
            /**
             * @default 30
             * @enum {integer}
             */
            fps: 24 | 25 | 30 | 50 | 60;
            /**
             * @default cover
             * @enum {string}
             */
            background_fit: "cover" | "contain" | "stretch";
        };
        /** @enum {string} */
        SourceAssetKind: "audio" | "background";
        /** @enum {string} */
        AssetKind: "audio" | "background" | "normalized_audio" | "subtitle" | "video";
        Asset: {
            id: components["schemas"]["Uuid"];
            project_id: components["schemas"]["Uuid"];
            kind: components["schemas"]["AssetKind"];
            original_filename?: string | null;
            media_type: string;
            bytes: number;
            sha256: string;
            duration_ms?: number | null;
            width?: number | null;
            height?: number | null;
            /** Format: uri-reference */
            readonly content_url?: string;
            created_at: components["schemas"]["Timestamp"];
        };
        StartTranscriptionRequest: {
            /**
             * @description BCP 47 language hint or `auto`
             * @default auto
             */
            language: string;
            /**
             * @description Server allow-listed model profile, not an arbitrary model path
             * @default configured-default
             */
            model: string;
            initial_prompt?: string | null;
            /** @default true */
            vad_enabled: boolean;
        };
        /** @enum {string} */
        TranscriptSource: "whisper" | "edited" | "imported";
        TranscriptRevision: {
            id: components["schemas"]["Uuid"];
            project_id: components["schemas"]["Uuid"];
            revision: number;
            source: components["schemas"]["TranscriptSource"];
            language: string;
            duration_ms: number;
            cues: components["schemas"]["TranscriptCue"][];
            transcriber?: components["schemas"]["TranscriberMetadata"] | null;
            created_at: components["schemas"]["Timestamp"];
        };
        ReplaceTranscriptRequest: {
            language: string;
            duration_ms: number;
            cues: components["schemas"]["TranscriptCue"][];
        };
        TranscriptCue: {
            id: components["schemas"]["Uuid"];
            start_ms: number;
            end_ms: number;
            words: components["schemas"]["TimedWord"][];
        };
        TimedWord: {
            id: components["schemas"]["Uuid"];
            text: string;
            start_ms: number;
            end_ms: number;
            readonly confidence?: number | null;
        };
        TranscriberMetadata: {
            /** @constant */
            engine: "faster-whisper";
            model: string;
            model_revision: string;
            language_probability: number;
        };
        StartRenderRequest: {
            transcript_revision: number;
            preset: components["schemas"]["RenderPreset"];
            quality: components["schemas"]["RenderQuality"];
            /** @description Optional per-render override; null uses project defaults */
            video_settings?: components["schemas"]["VideoSettings"] | null;
            typography: components["schemas"]["TypographySettings"];
            animation: components["schemas"]["AnimationSettings"];
            /** @default false */
            include_debug_ass: boolean;
        };
        /** @enum {string} */
        RenderPreset: "clean_karaoke" | "focus_word" | "kinetic_pop";
        /** @enum {string} */
        RenderQuality: "draft" | "final";
        TypographySettings: {
            /** @description Server allow-listed bundled font family */
            font_family: string;
            font_size: number;
            primary_color: components["schemas"]["HexColor"];
            highlight_color: components["schemas"]["HexColor"];
            outline_color: components["schemas"]["HexColor"];
            /** @default 2 */
            outline_width: number;
            /** @enum {string} */
            alignment: "top" | "center" | "bottom";
            margin_v: number;
        };
        AnimationSettings: {
            intensity: number;
            fade_in_ms: number;
            fade_out_ms: number;
        };
        HexColor: string;
        RenderAccepted: {
            render_id: components["schemas"]["Uuid"];
            job: components["schemas"]["Job"];
            /** Format: uri-reference */
            render_url: string;
        };
        /** @enum {string} */
        RenderStatus: "queued" | "running" | "succeeded" | "failed" | "cancelled";
        Render: {
            id: components["schemas"]["Uuid"];
            project_id: components["schemas"]["Uuid"];
            job_id: components["schemas"]["Uuid"];
            transcript_revision: number;
            status: components["schemas"]["RenderStatus"];
            settings: components["schemas"]["StartRenderRequest"];
            output?: components["schemas"]["RenderOutput"] | null;
            error?: components["schemas"]["JobError"] | null;
            created_at: components["schemas"]["Timestamp"];
            completed_at?: components["schemas"]["Timestamp"] | null;
        };
        RenderOutput: {
            video_asset: components["schemas"]["Asset"];
            subtitle_asset?: components["schemas"]["Asset"] | null;
            duration_ms: number;
            width: number;
            height: number;
        };
        JobAccepted: {
            job: components["schemas"]["Job"];
            /** Format: uri-reference */
            job_url: string;
            /** Format: uri-reference */
            events_url: string;
        };
        /** @enum {string} */
        JobType: "transcribe" | "render";
        /** @enum {string} */
        JobStatus: "queued" | "running" | "cancelling" | "succeeded" | "failed" | "cancelled";
        Job: {
            id: components["schemas"]["Uuid"];
            type: components["schemas"]["JobType"];
            status: components["schemas"]["JobStatus"];
            /** @enum {string} */
            phase: "queued" | "validating" | "normalizing" | "transcribing" | "post_processing" | "subtitle_compiling" | "encoding" | "finalizing" | "complete" | "failed" | "cancelled";
            progress: number;
            attempt: number;
            max_attempts: number;
            cancellable: boolean;
            result?: {
                [key: string]: unknown;
            } | null;
            error?: components["schemas"]["JobError"] | null;
            created_at: components["schemas"]["Timestamp"];
            started_at?: components["schemas"]["Timestamp"] | null;
            finished_at?: components["schemas"]["Timestamp"] | null;
        };
        JobError: {
            code: string;
            message: string;
            retryable: boolean;
            diagnostic_id?: string | null;
        };
        JobEvent: {
            job_id: components["schemas"]["Uuid"];
            sequence: number;
            status: components["schemas"]["JobStatus"];
            phase: string;
            progress: number;
            message?: string | null;
            occurred_at: components["schemas"]["Timestamp"];
        };
        ValidationIssue: {
            /** @example cues[2].words[4].end_ms */
            path: string;
            message: string;
        };
        Problem: {
            /** Format: uri-reference */
            type: string;
            title: string;
            status: number;
            code: string;
            detail: string;
            /** Format: uri-reference */
            instance?: string;
            request_id: components["schemas"]["Uuid"];
            issues?: components["schemas"]["ValidationIssue"][];
        };
    };
    responses: {
        /** @description Invalid request syntax or fields */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Missing or invalid authentication */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Resource is absent or not visible to the current owner */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Request conflicts with current resource state or idempotency record */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Upload exceeds configured byte or duration limits */
        PayloadTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description File media type, container, codec, or decoded content is unsupported */
        UnsupportedMedia: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Request is syntactically valid but violates domain or media invariants */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Required dependency or capability is unavailable */
        ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        ProjectId: components["schemas"]["Uuid"];
        JobId: components["schemas"]["Uuid"];
        RenderId: components["schemas"]["Uuid"];
        ArtifactId: components["schemas"]["Uuid"];
        /** @description Opaque client-generated key scoped to owner and operation */
        IdempotencyKey: string;
        /** @description Opaque client-generated key scoped to owner and operation */
        OptionalIdempotencyKey: string;
        /** @description ETag returned with the active transcript revision */
        IfMatch: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getLiveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ready to serve applicable work */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listProjects: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: {
                /** @description Opaque client-generated key scoped to owner and operation */
                "Idempotency-Key"?: components["parameters"]["OptionalIdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectRequest"];
            };
        };
        responses: {
            /** @description Project created */
            201: {
                headers: {
                    /** @description Canonical project URL */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProjectRequest"];
            };
        };
        responses: {
            /** @description Updated project */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    uploadProjectAsset: {
        parameters: {
            query?: never;
            header?: {
                /** @description Opaque client-generated key scoped to owner and operation */
                "Idempotency-Key"?: components["parameters"]["OptionalIdempotencyKey"];
            };
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    kind: components["schemas"]["SourceAssetKind"];
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Asset stored and activated */
            201: {
                headers: {
                    /** @description Canonical asset metadata URL */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Asset"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMedia"];
        };
    };
    startTranscription: {
        parameters: {
            query?: never;
            header: {
                /** @description Opaque client-generated key scoped to owner and operation */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartTranscriptionRequest"];
            };
        };
        responses: {
            /** @description Transcription job accepted */
            202: {
                headers: {
                    /** @description Canonical job URL */
                    Location?: string;
                    /** @description Suggested polling interval in seconds */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobAccepted"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    getActiveTranscript: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active transcript revision */
            200: {
                headers: {
                    /** @description Revision validator required for an update */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscriptRevision"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    replaceActiveTranscript: {
        parameters: {
            query?: never;
            header: {
                /** @description ETag returned with the active transcript revision */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplaceTranscriptRequest"];
            };
        };
        responses: {
            /** @description New active transcript revision */
            200: {
                headers: {
                    /** @description Validator for this new revision */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscriptRevision"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description The supplied ETag does not identify the active revision */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "https://lyrit-loom.local/problems/revision-conflict",
                     *       "title": "Transcript revision conflict",
                     *       "status": 412,
                     *       "code": "revision_conflict",
                     *       "detail": "The transcript changed after this editor loaded it.",
                     *       "request_id": "8286d1f6-05ab-4f84-a8bb-e47f33f9bb7d"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            422: components["responses"]["UnprocessableEntity"];
            /** @description If-Match header is required */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    startRender: {
        parameters: {
            query?: never;
            header: {
                /** @description Opaque client-generated key scoped to owner and operation */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartRenderRequest"];
            };
        };
        responses: {
            /** @description Render accepted */
            202: {
                headers: {
                    /** @description Canonical render URL */
                    Location?: string;
                    /** @description Suggested polling interval in seconds */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RenderAccepted"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    getRender: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                render_id: components["parameters"]["RenderId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Render resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Render"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    streamJobEvents: {
        parameters: {
            query?: never;
            header?: {
                "Last-Event-ID"?: string;
            };
            path: {
                job_id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream */
            200: {
                headers: {
                    "Cache-Control"?: "no-cache";
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "job_id": "e1c34fb8-fc84-46a8-b353-361276f59751",
                     *       "sequence": 17,
                     *       "status": "running",
                     *       "phase": "encoding",
                     *       "progress": 0.64,
                     *       "message": "Rendering video",
                     *       "occurred_at": "2026-07-16T18:20:12Z"
                     *     }
                     */
                    "text/event-stream": components["schemas"]["JobEvent"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    cancelJob: {
        parameters: {
            query?: never;
            header: {
                /** @description Opaque client-generated key scoped to owner and operation */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                job_id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancellation accepted or already requested */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    downloadArtifact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: components["parameters"]["ArtifactId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Artifact bytes */
            200: {
                headers: {
                    /** @example attachment; filename="lyric-video.mp4" */
                    "Content-Disposition"?: string;
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                    "video/mp4": string;
                    "text/x-ssa": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
}
